server:
  port:8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: Sikun@4862

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true